# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/openconfig/gnoi/interface/interface.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from github.com.openconfig.gnoi.types import types_pb2 as github_dot_com_dot_openconfig_dot_gnoi_dot_types_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='github.com/openconfig/gnoi/interface/interface.proto',
  package='gnoi.interface',
  syntax='proto3',
  serialized_options=b'\322>\0050.1.0',
  serialized_pb=b'\n4github.com/openconfig/gnoi/interface/interface.proto\x12\x0egnoi.interface\x1a,github.com/openconfig/gnoi/types/types.proto\"K\n\x16SetLoopbackModeRequest\x12#\n\tinterface\x18\x01 \x01(\x0b\x32\x10.gnoi.types.Path\x12\x0c\n\x04mode\x18\x02 \x01(\t\"\x19\n\x17SetLoopbackModeResponse\"=\n\x16GetLoopbackModeRequest\x12#\n\tinterface\x18\x01 \x01(\x0b\x32\x10.gnoi.types.Path\"\'\n\x17GetLoopbackModeResponse\x12\x0c\n\x04mode\x18\x01 \x01(\t\"D\n\x1d\x43learInterfaceCountersRequest\x12#\n\tinterface\x18\x01 \x03(\x0b\x32\x10.gnoi.types.Path\" \n\x1e\x43learInterfaceCountersResponse2\xd2\x02\n\tInterface\x12\x64\n\x0fSetLoopbackMode\x12&.gnoi.interface.SetLoopbackModeRequest\x1a\'.gnoi.interface.SetLoopbackModeResponse\"\x00\x12\x64\n\x0fGetLoopbackMode\x12&.gnoi.interface.GetLoopbackModeRequest\x1a\'.gnoi.interface.GetLoopbackModeResponse\"\x00\x12y\n\x16\x43learInterfaceCounters\x12-.gnoi.interface.ClearInterfaceCountersRequest\x1a..gnoi.interface.ClearInterfaceCountersResponse\"\x00\x42\x08\xd2>\x05\x30.1.0b\x06proto3'
  ,
  dependencies=[github_dot_com_dot_openconfig_dot_gnoi_dot_types_dot_types__pb2.DESCRIPTOR,])




_SETLOOPBACKMODEREQUEST = _descriptor.Descriptor(
  name='SetLoopbackModeRequest',
  full_name='gnoi.interface.SetLoopbackModeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='gnoi.interface.SetLoopbackModeRequest.interface', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='gnoi.interface.SetLoopbackModeRequest.mode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=193,
)


_SETLOOPBACKMODERESPONSE = _descriptor.Descriptor(
  name='SetLoopbackModeResponse',
  full_name='gnoi.interface.SetLoopbackModeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=220,
)


_GETLOOPBACKMODEREQUEST = _descriptor.Descriptor(
  name='GetLoopbackModeRequest',
  full_name='gnoi.interface.GetLoopbackModeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='gnoi.interface.GetLoopbackModeRequest.interface', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=283,
)


_GETLOOPBACKMODERESPONSE = _descriptor.Descriptor(
  name='GetLoopbackModeResponse',
  full_name='gnoi.interface.GetLoopbackModeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='gnoi.interface.GetLoopbackModeResponse.mode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=324,
)


_CLEARINTERFACECOUNTERSREQUEST = _descriptor.Descriptor(
  name='ClearInterfaceCountersRequest',
  full_name='gnoi.interface.ClearInterfaceCountersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='gnoi.interface.ClearInterfaceCountersRequest.interface', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=394,
)


_CLEARINTERFACECOUNTERSRESPONSE = _descriptor.Descriptor(
  name='ClearInterfaceCountersResponse',
  full_name='gnoi.interface.ClearInterfaceCountersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=428,
)

_SETLOOPBACKMODEREQUEST.fields_by_name['interface'].message_type = github_dot_com_dot_openconfig_dot_gnoi_dot_types_dot_types__pb2._PATH
_GETLOOPBACKMODEREQUEST.fields_by_name['interface'].message_type = github_dot_com_dot_openconfig_dot_gnoi_dot_types_dot_types__pb2._PATH
_CLEARINTERFACECOUNTERSREQUEST.fields_by_name['interface'].message_type = github_dot_com_dot_openconfig_dot_gnoi_dot_types_dot_types__pb2._PATH
DESCRIPTOR.message_types_by_name['SetLoopbackModeRequest'] = _SETLOOPBACKMODEREQUEST
DESCRIPTOR.message_types_by_name['SetLoopbackModeResponse'] = _SETLOOPBACKMODERESPONSE
DESCRIPTOR.message_types_by_name['GetLoopbackModeRequest'] = _GETLOOPBACKMODEREQUEST
DESCRIPTOR.message_types_by_name['GetLoopbackModeResponse'] = _GETLOOPBACKMODERESPONSE
DESCRIPTOR.message_types_by_name['ClearInterfaceCountersRequest'] = _CLEARINTERFACECOUNTERSREQUEST
DESCRIPTOR.message_types_by_name['ClearInterfaceCountersResponse'] = _CLEARINTERFACECOUNTERSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetLoopbackModeRequest = _reflection.GeneratedProtocolMessageType('SetLoopbackModeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETLOOPBACKMODEREQUEST,
  '__module__' : 'github.com.openconfig.gnoi.interface.interface_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.interface.SetLoopbackModeRequest)
  })
_sym_db.RegisterMessage(SetLoopbackModeRequest)

SetLoopbackModeResponse = _reflection.GeneratedProtocolMessageType('SetLoopbackModeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETLOOPBACKMODERESPONSE,
  '__module__' : 'github.com.openconfig.gnoi.interface.interface_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.interface.SetLoopbackModeResponse)
  })
_sym_db.RegisterMessage(SetLoopbackModeResponse)

GetLoopbackModeRequest = _reflection.GeneratedProtocolMessageType('GetLoopbackModeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETLOOPBACKMODEREQUEST,
  '__module__' : 'github.com.openconfig.gnoi.interface.interface_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.interface.GetLoopbackModeRequest)
  })
_sym_db.RegisterMessage(GetLoopbackModeRequest)

GetLoopbackModeResponse = _reflection.GeneratedProtocolMessageType('GetLoopbackModeResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETLOOPBACKMODERESPONSE,
  '__module__' : 'github.com.openconfig.gnoi.interface.interface_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.interface.GetLoopbackModeResponse)
  })
_sym_db.RegisterMessage(GetLoopbackModeResponse)

ClearInterfaceCountersRequest = _reflection.GeneratedProtocolMessageType('ClearInterfaceCountersRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLEARINTERFACECOUNTERSREQUEST,
  '__module__' : 'github.com.openconfig.gnoi.interface.interface_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.interface.ClearInterfaceCountersRequest)
  })
_sym_db.RegisterMessage(ClearInterfaceCountersRequest)

ClearInterfaceCountersResponse = _reflection.GeneratedProtocolMessageType('ClearInterfaceCountersResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLEARINTERFACECOUNTERSRESPONSE,
  '__module__' : 'github.com.openconfig.gnoi.interface.interface_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.interface.ClearInterfaceCountersResponse)
  })
_sym_db.RegisterMessage(ClearInterfaceCountersResponse)


DESCRIPTOR._options = None

_INTERFACE = _descriptor.ServiceDescriptor(
  name='Interface',
  full_name='gnoi.interface.Interface',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=431,
  serialized_end=769,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetLoopbackMode',
    full_name='gnoi.interface.Interface.SetLoopbackMode',
    index=0,
    containing_service=None,
    input_type=_SETLOOPBACKMODEREQUEST,
    output_type=_SETLOOPBACKMODERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLoopbackMode',
    full_name='gnoi.interface.Interface.GetLoopbackMode',
    index=1,
    containing_service=None,
    input_type=_GETLOOPBACKMODEREQUEST,
    output_type=_GETLOOPBACKMODERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ClearInterfaceCounters',
    full_name='gnoi.interface.Interface.ClearInterfaceCounters',
    index=2,
    containing_service=None,
    input_type=_CLEARINTERFACECOUNTERSREQUEST,
    output_type=_CLEARINTERFACECOUNTERSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INTERFACE)

DESCRIPTOR.services_by_name['Interface'] = _INTERFACE

# @@protoc_insertion_point(module_scope)
