# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from github.com.openconfig.gnoi.interface import interface_pb2 as github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2


class InterfaceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetLoopbackMode = channel.unary_unary(
                '/gnoi.interface.Interface/SetLoopbackMode',
                request_serializer=github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.SetLoopbackModeRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.SetLoopbackModeResponse.FromString,
                )
        self.GetLoopbackMode = channel.unary_unary(
                '/gnoi.interface.Interface/GetLoopbackMode',
                request_serializer=github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.GetLoopbackModeRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.GetLoopbackModeResponse.FromString,
                )
        self.ClearInterfaceCounters = channel.unary_unary(
                '/gnoi.interface.Interface/ClearInterfaceCounters',
                request_serializer=github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.ClearInterfaceCountersRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.ClearInterfaceCountersResponse.FromString,
                )


class InterfaceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def SetLoopbackMode(self, request, context):
        """SetLoopbackMode is used to set the mode of loopback on a interface.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoopbackMode(self, request, context):
        """GetLoopbackMode is used to get the mode of loopback on a interface.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearInterfaceCounters(self, request, context):
        """ClearInterfaceCounters will reset the counters for the provided interface.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetLoopbackMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLoopbackMode,
                    request_deserializer=github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.SetLoopbackModeRequest.FromString,
                    response_serializer=github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.SetLoopbackModeResponse.SerializeToString,
            ),
            'GetLoopbackMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoopbackMode,
                    request_deserializer=github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.GetLoopbackModeRequest.FromString,
                    response_serializer=github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.GetLoopbackModeResponse.SerializeToString,
            ),
            'ClearInterfaceCounters': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearInterfaceCounters,
                    request_deserializer=github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.ClearInterfaceCountersRequest.FromString,
                    response_serializer=github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.ClearInterfaceCountersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gnoi.interface.Interface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Interface(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def SetLoopbackMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gnoi.interface.Interface/SetLoopbackMode',
            github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.SetLoopbackModeRequest.SerializeToString,
            github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.SetLoopbackModeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLoopbackMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gnoi.interface.Interface/GetLoopbackMode',
            github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.GetLoopbackModeRequest.SerializeToString,
            github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.GetLoopbackModeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearInterfaceCounters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gnoi.interface.Interface/ClearInterfaceCounters',
            github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.ClearInterfaceCountersRequest.SerializeToString,
            github_dot_com_dot_openconfig_dot_gnoi_dot_interface_dot_interface__pb2.ClearInterfaceCountersResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
